### ISSUE TITLE
Network Threat Analytics - Traffic Drop Detector

### ISSUE THREAD

**Issue by dreamtalen** [antrea-io/theia#143]
### Purpose

Traffic Drop Detector is used to detect unreasonable amount of flows dropped or blocked by Network Policy for each endpoint, and reporting alerts to admins. It helps identify potential issues with the Network Policy, as well as helps identify potential security threats and take appropriate action to mitigate them.

### Tasks

P0 items:

- [x] Add the Snowflake UDF implementation of Traffic Drop Detector, which works with the Snowflake datasource. We likely only check in the initial/one-time version for now, which needs to be triggered by user like Policy Recommendation. - #148 

P1 items:

- [ ] Add the Spark implementation of Traffic Drop Detector, which works with the ClickHouse datasource.
WIP, probably targeting ~~v0.6~~v0.7 release.
- [ ] Add the periodical version of Traffic Drop Detector on Snowflake. We will leverage Snowflake Task to execute Traffic Drop UDF periodically like once a day, and write down the detection result into a table. This will need to implement a series of CLI commands to let user create/check/delete Snowflake Task, check detection result, etc.
~~WIP, probably targeting v0.6 release.~~ We are investigating the snowpark implementation of NTA/NPR, lower the priority of this item.

**Comment by dreamtalen** [comment]
Closed this issue for now as P0 items finished.
