### ISSUE TITLE
App Visibility Grafana dashboard enhancement

### ISSUE THREAD

**Issue by heanlan** [antrea-io/theia#58]
Add capabilities that might provide users insights more oriented to understand how applications deployed in a k8s cluster communicate.

P0 items:
- [x] Add Pod/Service Namespace and port metadata into dashboard - #57 
- [x] Have user-friendly names for columns used in tables and filters. For instance "flowEndSecondsFromSourceNode" could be displayed as "end of flow as reported by source"  - #83 
- [x] For time-series diagram, do not connect discrete points with line, as they might tell some misleading information, showing throughput is growing/decreasing linearly, which might not be true. For legend of time-series diagram, do not show the "mean" value on the right hand side, as its internal calculation logic is not accurate for our use case. - #83 
- [x] For "FlowEndReason" field, do the value mapping from int to string. - #83 
- [x] Save configurations/settings of Grafana at runtime, and re-apply those settings when restart Pods. We should expose this option through Helm chart to users, determining whether they would like to save and re-apply the settings. #84 

P1 items:
- [x]  Create a customized "Home page" dashboard, which includes basic introduction to network flow-visibility(pointer to documentation), cluster network overview(diagram monitoring network metrics), links to all the other dashboard #101 
- [ ] Enable adding users by sending email invitations; require configuring the Grafana server to authenticate on mail server
- [x] Aggregate traffic by Pod labels.
