### ISSUE TITLE
e2e test coverage improvement for policy recommendation

### ISSUE THREAD

**Issue by dreamtalen** [antrea-io/theia#72]
### Background
Currently, our e2e test for policy recommendation only covers a single execution of `run/status/retrieve` CLI commands. And only one single Pod-to-Pod flow traffic is generated for the test of the `retrieve` command. 

### Tasks
To have better e2e test coverage, we are planning to add these test cases:

- [x] Add coverage for `list` and `delete` command. #49
- [ ] Add test cases covering policy recommendations for Pod-to-Service, and Pod-to-External flows.
- [ ] Add coverage for the failed cases.

### Notes
Because a recommendation job may take several minutes to complete, to minimize the test running time, I'm considering adding the Pod-to-Service and Pod-to-External flows into the current test of the `retrieve` command instead of creating separate test cases.

To test the failed cases, we could simulate a test case where the Driver Pod is destroyed and unavailable when the policy recommendation job is still running. Then we could check the Status and FailedReason of this job through the `status` command.
